MAX_NOTE,MIN_NOTE = 109,21

NOTE_PRECISION = 64
LATENT_DIM = 128
INPUT_DIM = MAX_NOTE-MIN_NOTE

SECTION = 8 
# TIME_STEP = SECTION * TICKS_PER_MEASURE
PIX_PER_SECTION = 192 #192 is least common multiple of 64 and 96, which are multiples of most time signatures
TIME_STEP = PIX_PER_SECTION*SECTION
DROP_OUT_RATE = 0.1
BATCH_SIZE = 128

TRAIN_STEPS = 40
EPOCHS_PER_STEP = 16
START_SAVE = TRAIN_STEPS//4
